[package]
name = "hammer-shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = true

[dependencies]
nix = { version = "0.24.1" }
